version: '3.8'

services:
  db:
    image: postgres:16
    container_name: museum-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: museum_app
    ports:
      - "5432:5432"
    volumes:
      - museum-db-data:/var/lib/postgresql/data

volumes:
  museum-db-data:
